### ISSUE TITLE
Issue in Mac

### ISSUE THREAD

**Issue by browneye1826** [Vi-debug/Google-Search-Type#2]
Hi there :)
Would love to use this extension; for some reason though its not working for me 😢
I'm on a Mac: When I do <kbd>⌘ Command</kbd>+<kbd>⇧ Shift</kbd>+<kbd>P</kbd> it shows the 'Google it' extension in the menu but when I click it nothing happens. I also tried <kbd>⌘ Command</kbd>+<kbd>;</kbd> which doesn't do anything at all.
Please advise, with thanks.

**Comment by Pall-v** [comment]
Looks like the keybinding was updated to "ctrl+'" in this commit: https://github.com/Vi-debug/Google-Search-Type/commit/e35d2dceaecc00c2a10c0a1a05f6bd71fdddf71e

The documentation needs to be updated.

**Comment by Vi-debug** [comment]
I updated Readme. Thanks
